### ISSUE TITLE
Passing JobCollection object to new Job() fails, only collection name string works. 

### ISSUE THREAD

**Issue by rclai** [vsivsi/meteor-job-collection#69] opened 2015-03-25 13:24 UTC
The first parameter is supposed to be a string on:

```js
var job = new Job('collectionName', 'jobType', { a: 1, b: 2 });
```

The documentation here is showing otherwise.

https://github.com/vsivsi/meteor-job/issues/6

**Comment by vsivsi** [comment] 2015-03-25 18:12
Hi, actually it should work either way, as a name string or jc object. 

https://github.com/vsivsi/meteor-job/blob/master/src/job_class.coffee#L478

I'll look at this again and make sure I didn't screw his up.

**Comment by rclai** [comment] 2015-03-25 18:43
Passing a jc object fails.

**Comment by vsivsi** [comment] 2015-03-25 19:02
Okay, that's a bug. I'll fix this today.

**Comment by rclai** [comment] 2015-03-25 19:34
Thanks.

**Comment by vsivsi** [comment] 2015-03-25 20:59
Hi @rclai, I'm having trouble reproducing this issue.  There is a unit test that covers the case where the `jc` is a JobCollection object here: https://github.com/vsivsi/meteor-job-collection/blob/master/job_collection_tests.coffee#L110

In fact, all of the jobs in the unit tests are constructed this way (using a `jc` object as the first parameter).  The unit tests all pass on my machines.

Can you please show me some code that causes the problem for you, and give me the exact error message you receive so I can reproduce what you are seeing?

Thanks

**Comment by vsivsi** [comment] 2015-03-25 21:53
Hi, I see your code in the comment here: https://github.com/vsivsi/meteor-job/issues/6
And the error message included. It looks to me like maybe there are some mixed up versions.

What version of job-collection are you using?  And what version of meteor-job?  Are you using job-collection from Atmosphere, or a local version in your package directory from a git clone?  
 
Here's what I've done to try to reproduce this:

```bash
meteor create newJobTest
cd newJobTest
meteor install vsivsi:job-collection
# Make edits below, then run:
meteor
```
Now edit the default `newjobtest.js` file to add at the top of the file:
```js
PartCrawlJobs = new JobCollection('partCrawlJobs', {
  noCollectionSuffix: true
});

if (Meteor.isServer) {
  // Job write permissions
  PartCrawlJobs.allow({
    admin: function (userId, method, params) {
      return !!userId;
    }
  });
}

var job = new Job(PartCrawlJobs, 'test', { a:1, b:2, c:3 });
```

I don't get any errors when I run this.

**Comment by rclai** [comment] 2015-03-25 22:54
Is it possible it doesn't work because the `Mongo.Collection` object was monkey-patched?

**Comment by vsivsi** [comment] 2015-03-25 23:06
I don't think so. My best guess at what might cause this is that you're either running an older pre-1.0 version of job-collection, or somehow the meteor-job subproject in the copy of job-collection you are using hasn't also been updated to v1.0. This is why I asked about how you've installed job-collection in your project. If it's from a git clone, then you're probably seeing a version compatibility problem.

**Comment by rclai** [comment] 2015-03-26 03:03
It was not cloned. It was `api.imply`'d from a local package I made as version 1.0.0.

**Comment by rclai** [comment] 2015-03-26 18:35
I need to downgrade to 0.0.18 for the meantime, I'll create a reproduction when I get the chance.

**Comment by vsivsi** [comment] 2015-03-26 19:17
Hi, okay.

Why do you need to downgrade?  It works fine using the string name like `new Job('jcName', ...)`, right?

Also, the old ’jc.createJob()` and `jc.makeJob()` calls should still work fine as before (with warnings). 

I've been thinking about this, and it seems that the only way to get the error you are seeing would be if the global `Job` object is still somehow being defined using a pre-1.0 version of Meteor Job, while `JobCollection` is being defined by version 1.0 of job-collection. If you are using Atmosphere to add job-collection to your app, the. This shouldn't happen, unless you are also somehow manually loading the meteor-job npm package, overriding the version that comes with job-collection. 

This is what I meant above when I said that your versions seem to be mismatched. 

Anyway, if you can share a minimal Meteor application that reproduces the error, that would be extremely helpful.  Thanks, V

**Comment by chmac** [comment] 2015-05-23 17:23
This might be related to meteor/meteor/issues/4170 which says that unless you explicitly require `vsivsi:job-collection@1.1.2` then you'll get an old version when you run package-tests, and maybe in other cases. Don't know if it's relevant or not, but whenever I see something about package versions, I always think of this issue. I'd recommend explicitly adding a version to your `package.js` file if you don't already have one anyway, as it guarantees consistent behaviour.

**Comment by vsivsi** [comment] 2015-05-23 22:09
@chmac. Thanks for the heads-up on that. I've seen multiple reported issues since the 1.0 releases of my packages that I can't reproduce and seem like out of date versions are somehow being used.  This gives me another line of questioning to try and figure out what is wrong!

**Comment by rclai** [comment] 2015-05-23 22:25
I think that this might've been the issue I was dealing with, but I'm not sure. I'll have to report back next week.

**Comment by vsivsi** [comment] 2015-06-13 20:46
I think all of these issues have been resolved, so I'm closing this.  @rclai  Feel free to reopen this if you are still having problems with the latest version.

**Closed by vsivsi** 2015-06-13 20:46 UTC
Labels: can't reproduce
