### ISSUE TITLE
Error: Method not found [404]

### ISSUE THREAD

**Issue by meteorjs3000** [vsivsi/meteor-job-collection#65] opened 2015-03-10 13:45 UTC
When my app starts, I see the following error message being displayed repeatedly as the app runs. How do we find out the name of the missing method?

    JobQueue: Received error from getWork():  { [Error: Method not found [404]]
      error: 404,
      reason: 'Method not found',
      details: undefined,
      message: 'Method not found [404]',
      errorType: 'Meteor.Error' }

**Comment by vsivsi** [comment] 2015-03-10 19:54
Hi, thanks for your question.  Without knowing anything about what you are trying to do or how you are using job-collection, my best guess is that you are getting this because you have a mismatch between the name of the job-collection on your server and some client (either Meteor client or pure node.js client).

Workers on the server don't (or shouldn't) go through a Meteor method call to access the local job collection, although that is behavior that has changed in the implementation over time, so will depend on what version of job-collection you are using.

That was all a very long winded way of saying, it's probably a collection naming mismatch, but without being able to see the code that produces this error, I can only guess. 

If you can put together a minimal Meteor app that reproduces this error, I'd be happy to take a look.

**Comment by meteorjs3000** [comment] 2015-03-11 20:10
Thanks for your reply! My worker is a Meteor server running job-collections v0.0.18. 

I have it running something like

	var workers = Job.processJobs('jobQueue', 'jobType', { concurrency: 4 },
	  function (job, cb) {
	    doWork(function() {
	      cb();
	    });
	  }
	);

Running the code within `Meteor.startup` seems to solve the error. Will this be the recommended way of running `Job.processJobs` on a Meteor server?

**Comment by vsivsi** [comment] 2015-03-12 00:29
Hi, yes you'll get 404 errors if you try to call a Meteor method before the server has started up and the servers-side collection has been able to initialize itself.

See for example how this is done in the same app:

https://github.com/vsivsi/meteor-file-job-sample-app/blob/master/sample.coffee#L379

**Comment by vsivsi** [comment] 2015-03-24 00:12
Closing this.

**Closed by vsivsi** 2015-03-24 00:12 UTC
Labels: question

**Comment by randomnerd** [comment] 2015-08-04 16:03
Hi there!

Got exact same error while trying to set things up for a pure node.js worker. What am I doing wrong?

Meteor server code:
```javascript
Jobs = JobCollection('jobQueue');
Jobs.allow({
  admin: function(userId, method, params) {
    return (userId ? true : false);
  }
});

Meteor.startup(function() {
  Meteor.publish('allJobs', function() {
    return Jobs.find({});
  });

  return Jobs.startJobServer();
});
```

node worker:
```javascript
///////////////////
// node.js Worker
var DDP = require('ddp');
var DDPlogin = require('ddp-login');
var Job = require('meteor-job');

// `Job` here has essentially the same API as JobCollection on Meteor.
// In fact, job-collection is built on top of the 'meteor-job' npm package!

// Setup the DDP connection
var ddp = new DDP({
    host: "localhost",
  port: 3000,
  use_ejson: true
});

// Connect Job with this DDP session
Job.setDDP(ddp);

// Open the DDP connection
ddp.connect(function (err) {
  if (err) throw err;
  // Call below will prompt for email/password if an
  // authToken isn't available in the process environment
  DDPlogin(ddp, {
    method: 'account',
    account: 'admin@example.com',
    pass: '123qwe123'
  }, function (err, token) {
    if (err) throw err;
    // We're in!
    // Create a worker to get sendMail jobs from 'myJobQueue'
    // This will keep running indefinitely, obtaining new work
    // from the server whenever it is available.
    // Note: If this worker was running within the Meteor environment,
    // Then only the call below is necessary to setup a worker!
    var workers = Job.processJobs('myJobQueue', 'sendEmail',
      function (job, cb) {
        // This will only be called if a
        // 'sendEmail' job is obtained
        var email = job.data; // Only one email per job
        sendEmail(email.address, email.subject, email.message,
          function(err) {
            if (err) {
              job.log("Sending failed with error" + err,
                {level: 'warning'});
              job.fail("" + err);
            } else {
              job.done();
            }
            // Be sure to invoke the callback
            // when work on this job has finished
            cb();
          }
        );
      }
    );
  });
});
```

Thanks!

**Comment by vsivsi** [comment] 2015-08-04 16:17
Your names don't match.  On the server you name your JobCollection "jobQueue". In the worker your call to `processJobs()` is tryin to connect to a JobCollection named "myJobQueue"

**Comment by randomnerd** [comment] 2015-08-04 16:18
oh. i feel so stupid now :) thanks!
