### ISSUE TITLE
Error: use "new" to construct a Mongo.Collection when using collection-hooks package

### ISSUE THREAD

**Issue by evenfrost** [vsivsi/meteor-job-collection#58] opened 2015-01-30 15:44 UTC
Hello,
I've got following error in my Meteor app after installing `matb33:collection-hooks` along with `meteor-job-collection`:
```
W20150130-18:34:34.668(3)? (STDERR)           
W20150130-18:34:34.669(3)? (STDERR) /home/evenfrost/.meteor/packages/meteor-tool/.1.0.40.170c9d1++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150130-18:34:34.669(3)? (STDERR) 						throw(ex);
W20150130-18:34:34.669(3)? (STDERR) 						      ^
W20150130-18:34:34.743(3)? (STDERR) Error: use "new" to construct a Mongo.Collection
W20150130-18:34:34.743(3)? (STDERR)     at JobCollection.Mongo.Collection (packages/mongo/collection.js:29:1)
W20150130-18:34:34.743(3)? (STDERR)     at JobCollectionBase (packages/vsivsi:job-collection/shared.coffee:89:5)
W20150130-18:34:34.744(3)? (STDERR)     at new JobCollection (packages/vsivsi:job-collection/server.coffee:19:7)
W20150130-18:34:34.744(3)? (STDERR)     at JobCollection (packages/vsivsi:job-collection/server.coffee:16:20)
W20150130-18:34:34.744(3)? (STDERR)     at app/lib/collections/jobs.js:1:49
W20150130-18:34:34.744(3)? (STDERR)     at app/lib/collections/jobs.js:3:3
W20150130-18:34:34.744(3)? (STDERR)     at /home/evenfrost/work/projects/sw/src/.meteor/local/build/programs/server/boot.js:205:10
W20150130-18:34:34.744(3)? (STDERR)     at Array.forEach (native)
W20150130-18:34:34.744(3)? (STDERR)     at Function._.each._.forEach (/home/evenfrost/.meteor/packages/meteor-tool/.1.0.40.170c9d1++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150130-18:34:34.744(3)? (STDERR)     at /home/evenfrost/work/projects/sw/src/.meteor/local/build/programs/server/boot.js:116:5
=> Exited with code: 8
```
Contents of `app/lib/collections/jobs.js`:
```javascript
reportJobs = JobCollection('reports');
```
(Tried with `new` as well.)
Meteor version is 1.0.3.1.

**Comment by evenfrost** [comment] 2015-01-30 16:01
When adding `matb33:collection-hooks` *before* `vsivsi:job-collection`, the issue goes away. Seems it is related to [this issue](https://github.com/meteor-velocity/velocity/issues/200), and collection hooks package may be initiator, though I'm not aware of CoffeeScript syntax to investigate `.coffee`s in the stack trace.

**Comment by vsivsi** [comment] 2015-01-30 20:24
Thanks for reporting this. I'm not a `matb33:collection-hooks` user, but JobCollection objects are a subclass of Mongo.Collection, so if adding the collection-hooks package after job-collection causes the underlying collection to be constructed without `new`, then that could be a problem. Having done no investigation on this, it sounds to me as though collection-hooks may be making some modifications to the Mongo.Collection Object (or shadowing it) that are incompatible with other packages then extending it further.  

I'll try to take a look at this over the weekend.  Thanks again.  -V

**Comment by vsivsi** [comment] 2015-01-30 21:21
Okay, this was pretty simple.  The problem is almost certainly with the way `collection-hooks` is implemented.  Here's the issue in a nutshell.

When you load `job-collection` first, a new object type is created (`JobCollection`) that is a subclass of `Mongo.Collection` as it is defined by the Meteor `mongo` package. Then when `collection-hooks` is loaded, it ***replaces*** the global `Mongo.Collection` constructor object with its own shadow implementation (that ultimately calls into the original).

The issue is that when your application then invokes `jc = new JobCollection();`, the definition of the global `Mongo.Collection` has changed, but the definition of the JobCollection constructor has captured the original definition of `Mongo.Collection` in its closure. So within the `JobCollection` constructor `assert(this instanceof Mongo.Collection);` fails because `this` is a instance of the original Meteor defined `Mongo.Collection` and `Mongo.Collection` is now the shadow `matb33:collection-hooks` defined constructor.

Literally the only way their "replace the global `Mongo.Collection`" strategy can work is if it is the very first package to load before any other packages that might create a closure or otherwise save a reference to the original Meteor supplied `Mongo.Collection` object.

IMO, Shadowing system supplied global objects is a poor practice because it will always lead to these types of issues.  Instead, they should probably create a `HookedCollection` subclass that provides their extended functionality, and let the developer decide if they want to: `Mongo.Collection = HookedCollection`, and suffer the consequences.

My 2c.

**Comment by vsivsi** [comment] 2015-01-30 21:42
FYI, I'm going to add a check in the `JobCollection` constructor to specifically detect this case and spit out a more informative fatal error than the one currently being thrown by the original `Mongo.Collection` constructor. This same issue also affects my other package `file-collection`, and I'll make the same change there.

**Comment by vsivsi** [comment] 2015-01-30 21:54
I've added the following Error to be thrown in this case:
```Error 'The global definition of Mongo.Collection has changed since the job-collection package was loaded. Please ensure that any packages that redefine Mongo.Collection are loaded before job-collection.'
```

**Comment by evenfrost** [comment] 2015-01-31 09:11
Yeah, I totally agree with you about shadowing stuff. Thanks a lot for investigation and info!

**Comment by leebenson** [comment] 2015-03-13 10:36
I've had this same issue with a couple of third-party packages - most recently with [Mongol](https://github.com/msavin/Mongol/)

I agree that it's poor practice, but it does seem to be a common. [Houston](https://github.com/gterrono/houston) that suffers from the same problem.

Is this something that can be solved within meteor-job-collection? Controlling pre-load package order may seem relatively trivial, but I don't think it's generally expected behavior that the order by which you add Meteor packages can have side-effects.

**Comment by vsivsi** [comment] 2015-03-13 16:55
Hi, if there was only one other package that did this, job-collection could probably work around it. But given that there are multiple other packages taking this approach, I'm not inclined to play "whack a mole" with them to make using them all seemless.

The code I've added here to emit an informative error message at startup is about the best I can do, I think. I still believe that shadowing Meteor standard calls with "enhanced" versions that cause compatibility issues with other packages is a bad practice of the part of those packages. I'm really not willing to do a lot of extra work to make that poor practice seem less objectionable.

**Comment by leebenson** [comment] 2015-03-13 17:02
@vsivsi totally understandable, it's not your problem to fix other packages... I'm just speculating if there's a "catch all" vs checking to see if the Mongo.Collection object has changed vs its original state... if not, then I guess it's just a case of defining `meteor/packages` order manually. Not a big deal, really.

**Comment by vsivsi** [comment] 2015-03-24 00:13
Closing this.

**Closed by vsivsi** 2015-03-24 00:13 UTC
Labels: question
