### ISSUE TITLE
Fixing "running" jobs that aren't running

### ISSUE THREAD

**Issue by aldeed** [vsivsi/meteor-job-collection#86] opened 2015-06-16 16:33 UTC
I'm using this and it's working well, but sometimes jobs get stuck at "running" state. I think it happens when a worker process is killed while working on it.

Is there (or could there be) a way to say "Workers should never take more than N time to do this task. If it's still running after that time, try to auto fix/restart."?

**Comment by vsivsi** [comment] 2015-06-16 19:14
Hi Eric, This just came up last week in another context:  https://github.com/vsivsi/meteor-job-collection/issues/82#issuecomment-110173008

Short answer is: this is by design. I couldn't figure out a simple set of built-in rules that I was really convinced would cover > 80% of situations, so I've left it to the developer to decide for each type of job, what the "zombie" running job policy should be. You can easily implement this server-side as a [repeating "reaper/cleanup" job](https://github.com/vsivsi/meteor-job-collection-playground/blob/master/play.coffee#L360-L402), or as a good old `Meteor.setInterval()` function. Something like this will do for simple situations:  

```javascript
var createReaper = function(jc, type, timeOut) {
   // jc: jobCollection, type: job type, timeOut in ms
   var autofail = function () {
      var stale = new Date(new Date() - timeOut);
      jc.find({ status: 'running', type: type, updated: { $lt: stale }}).forEach(function (job) {
         new Job(jc, job).fail("Timed out by autofail");       
      });
   };
   return Meteor.setInterval(autofail, timeOut);
};

var r1 = createReaper(myJobs, 'fastJob', 30000);
var r2 = createReaper(myJobs, 'longJob', 3600000);
```

Basing it on the `updated` field has the advantage that a job that is alive and calling either `job.log()` or `job.progress()` will never be autofailed, no matter how long it runs. So in that case, you could write fairly short timeouts for even long running jobs so long as they are written to check-in frequently with progress updates.

**Comment by aldeed** [comment] 2015-06-16 19:46
OK looks great, thanks. But any reason this couldn't be part of the package like this?

```js
var fastJobReaper = myJobCollection.createReaper('fastJob', 30000);
fastJobReaper.start(); // triggers setInterval
fastJobReaper.stop(); // triggers clearInterval
```

**Comment by aldeed** [comment] 2015-06-16 19:51
Also setInterval seems a bit safer that having an autofail job since the autofail job itself could get stuck in zombieland. :) But maybe that's being too paranoid.

**Comment by aldeed** [comment] 2015-06-16 19:59
Sorry one more thought. If this were built in, it might actually be better to provide the reaper timeout as a `processJobs` option (since the worker is best equipped to know how long processing each job type should take). Then the API can be simply `myJobCollection.startReaper()` and `myJobCollection.stopReaper()`. That might mean needing to store the timeout values in the database, though.

**Comment by vsivsi** [comment] 2015-06-16 20:21
It could be part of the package... Although if part of the package, rather than having a lot of independent setIntervals, I'd probably build it into the "promotion" mechanism as a separate "demotion" feature: https://github.com/vsivsi/meteor-job-collection/blob/master/src/server.coffee#L148

Doing that would require setting an `expires` attribute on the job when created, and then adding an `expiresAfter` field to the job document model that is reset whenever the `updated` field is updated on any running job. That way a simple single query could find and reap all of the zombies on each promote (demote) beat:
```javascript
jc.find({status: 'running', expiresAfter: { $lt: new Date()}})
   .forEach(function (job) {
      new Job(jc, job).fail("Timed out by autofail");       
   });
``` 

All of this is doable, and I almost implemented it from the beginning, but I was ultimately dissuaded by building in the state and mechanism for a policy that may well not cover many/most use cases.  For example, what if you really only want jobs to run for X minutes wall clock, regardless of if they are reporting progress?  Or, if this is built in, then should there be a way for a running job to formally request more time (and perhaps be rejected) as opposed to simply checking in (which automatically grants more time under the simple policy)?  Etc, etc.  There are lots of variations and I haven't been able to convince myself that any one of them crosses the mythical 80% threshold. 

So in the end I convinced myself that the simplest policy added just 10 lines of code to someone's app to implement, and made the dev explicitly aware of the choice they were making for each type of job, rather than having the system do it for them. In general, I'm wary of having automatic mechanisms that do things like cause jobs to fail.

BTW, I had a very similar internal debate regarding auto-cleanup of completed jobs. If you have repeating jobs that run every minute, you quickly build-up a lot of old finished jobs in the collection. It might be nice to have a way to automatically have those disappear every so often... Anyway, I drew the line at having any automatic processes that remove data.  Since every dev was probably going to need to confront this cleanup issue in any case, adding on handling the zombie jobs didn't seem too onerous.

Anyway, that's why it is the way it is.

**Comment by vsivsi** [comment] 2015-06-16 20:28
> it might actually be better to provide the reaper timeout as a processJobs option (since the worker is best equipped to know how long processing each job type should take).

This is a good point, although it would need to be lower level than `processJobs` (which is optional) and would be an option on [`getWork()`](https://github.com/vsivsi/meteor-job-collection#jcgetworktype-options-callback---anywhere)

Anyway that's an interesting idea...

**Comment by vsivsi** [comment] 2015-06-16 20:36
> Also setInterval seems a bit safer that having an autofail job since the autofail job itself could get stuck in zombieland. :) But maybe that's being too paranoid.

The autofail job is a repeating job that is re-added to the collection on each server restart (so it's immune from becoming a zombie due to a server crash). Since it runs on the server, it shouldn't ever become a zombie (fail to call `job.done()` or `job.fail()`) any other way. Obviously proper error handling is important for that job to be robust, but that's a universal truth!

**Comment by aldeed** [comment] 2015-06-16 20:37
That makes some sense.

I'm building an events/notifications package on top of this (will eventually be published), and in that case, it would be nice if I could simply pass through an optional timeout (and cleanup) value when they define a notifier (which correlates with getWork/processJobs).

It's true that I can implement that separately using your example, but since it feels like a common need, I thought it might be better built in.

Also your comment about it being more efficient when using the existing promotion polling kind of makes a good case for why it should NOT be done outside of the package.

I agree nothing should happen automatically, but if we pass an option that causes it to happen only for that type, that seems pretty safe.

**Comment by vsivsi** [comment] 2015-06-16 20:48
I'll think about your idea of having it be an option on getWork/processJobs. It would require two more (optional) bits of state in the job document, and a code change in the methods implementing `job.log` and `job.progress` in addition of the demotion logic to the promote function. Not a ton of work, and could be implemented without breaking any existing code, so worth seriously considering.

**Comment by vsivsi** [comment] 2015-06-16 23:18
On the `demote` branch.  https://github.com/vsivsi/meteor-job-collection/tree/demote

`processJobs()` now has an option `workTimeout: <ms>` that will cause a job to auto fail on the next promotion cycle if the worker doesn't call `job.progress()` or `job.log()` at least every `workTimeout` milliseconds before calling `job.done()` or `job.fail()` 

This is marked as version 1.2.0 in the `package.js` file, so you can use that in your versions file to select a git checkout of this branch in your `packages` directory.

Let me know what you think.

**Comment by rhyslbw** [comment] 2015-06-17 02:47
Awesome, glad to see this

**Comment by vsivsi** [comment] 2015-06-17 07:21
The only drawback of this implementation is that `job.progress()` and `job.log()` now each require two DB accesses in all cases to determine if a `workTimeout` exists on the job before updating it (so `expiresAfter` can be properly reset). These were each formerly just a single update, now they are find+update. Not ideal... but the periodic demotion logic is much simpler this way.

**Comment by aldeed** [comment] 2015-06-17 17:03
Great! I will try it out probably tomorrow. If the extra db read is problematic in situations with lots of logging/progress, maybe you could have an in-memory cache of workTimeout values by _id. It should be immutable (at least through the API) so could be safely cached.

**Comment by vsivsi** [comment] 2015-06-17 17:53
Frequently accessed records in MongoDB end up being effectively cached in memory anyway, since it uses memory mapped files with a LRU page replacement policy. That only really helps if the Mongo instance is on the local Meteor server though... I think this would only matter on a really heavily loaded server handling tons of simultaneous remote running jobs that update status very frequently. If it becomes an issue, a caching mechanism can be added later without much difficulty.

**Comment by vsivsi** [comment] 2015-07-23 09:09
Version 1.2.0 just released on Atmosphere implements the `workTimeout` feature described above.

**Closed by vsivsi** 2015-07-23 09:09 UTC
Labels: enhancement
